[2015-08-16 04:42:51] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/') #5 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-08-16 04:48:05] log.ERROR: exception 'ErrorException' with message 'Undefined variable: item' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:66 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(66): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 66, Array) #1 [internal function]: GenericController->performance('{}') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{}') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-08-16 04:48:29] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/{}', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/%7B%7D') #5 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-08-16 04:48:59] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/{{table}}" cannot reference variable name "table" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/{}', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/%7B%7D') #5 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-08-16 04:49:00] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/{{table}}" cannot reference variable name "table" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/{}', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/%7B%7D') #5 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-08-16 04:49:02] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/{{table}}" cannot reference variable name "table" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/{}', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/%7B%7D') #5 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-08-16 04:49:34] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/{{table}}" cannot reference variable name "table" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/{}', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/%7B%7D') #5 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-08-16 04:49:52] log.ERROR: exception 'ErrorException' with message 'Undefined variable: item' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:66 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(66): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 66, Array) #1 [internal function]: GenericController->performance('{}') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{}') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-08-16 04:58:01] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:73 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(73): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 73, Array) #1 [internal function]: GenericController->performance('{"tables":{"dat...') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":{"dat...') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-08-16 05:00:09] log.ERROR: exception 'ErrorException' with message 'Illegal offset type' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:69 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(69): Illuminate\Exception\Handler->handleError(2, 'Illegal offset ...', '/Applications/X...', 69, Array) #1 [internal function]: GenericController->performance('{"tables":{"dat...') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":{"dat...') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-08-16 05:00:15] log.ERROR: exception 'ErrorException' with message 'Illegal offset type' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:69 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(69): Illuminate\Exception\Handler->handleError(2, 'Illegal offset ...', '/Applications/X...', 69, Array) #1 [internal function]: GenericController->performance('{"tables":{"dat...') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":{"dat...') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-08-16 05:00:33] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:73 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(73): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 73, Array) #1 [internal function]: GenericController->performance('{"tables":{"dat...') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":{"dat...') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-08-16 05:01:22] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:74 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(74): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 74, Array) #1 [internal function]: GenericController->performance('{"tables":{"dat...') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":{"dat...') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-08-16 05:02:42] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:74 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(74): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 74, Array) #1 [internal function]: GenericController->performance('{"tables":{"dat...') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":{"dat...') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-08-16 05:02:44] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:74 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(74): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 74, Array) #1 [internal function]: GenericController->performance('{"tables":{"dat...') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":{"dat...') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-08-16 05:02:55] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:74 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(74): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 74, Array) #1 [internal function]: GenericController->performance('{"tables":{"dat...') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":{"dat...') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-08-16 05:03:03] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:73 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(73): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 73, Array) #1 [internal function]: GenericController->performance('{"tables":{"dat...') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":{"dat...') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-08-16 05:03:15] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:73 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(73): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 73, Array) #1 [internal function]: GenericController->performance('{"tables":{"dat...') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":{"dat...') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-08-16 05:03:49] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:73 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(73): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 73, Array) #1 [internal function]: GenericController->performance('{"tables":{"dat...') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":{"dat...') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-08-16 05:04:21] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:73 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(73): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 73, Array) #1 [internal function]: GenericController->performance('{"tables":{"dat...') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":{"dat...') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-08-16 05:04:50] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:73 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(73): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 73, Array) #1 [internal function]: GenericController->performance('{"tables":{"dat...') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":{"dat...') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-08-16 05:05:09] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:73 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(73): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 73, Array) #1 [internal function]: GenericController->performance('{"tables":{"dat...') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":{"dat...') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-08-16 05:05:21] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:74 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(74): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 74, Array) #1 [internal function]: GenericController->performance('{"tables":{"dat...') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":{"dat...') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-08-16 05:06:01] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:74 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(74): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 74, Array) #1 [internal function]: GenericController->performance('{"tables":{"dat...') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":{"dat...') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-08-16 05:06:14] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:74 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(74): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 74, Array) #1 [internal function]: GenericController->performance('{"tables":{"dat...') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":{"dat...') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-08-16 05:06:46] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:74 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(74): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 74, Array) #1 [internal function]: GenericController->performance('{"tables":{"dat...') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":{"dat...') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
