[2015-06-27 04:39:24] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-06-27 04:39:34] log.ERROR: exception 'ReflectionException' with message 'Class WebblogController does not exist' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Container\Container.php:308 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Container\Container.php(308): ReflectionClass->__construct('WebblogControll...') #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build('WebblogControll...', Array) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('WebblogControll...', Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(983): Illuminate\Foundation\Application->make('WebblogControll...') #4 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #11 {main} [] []
[2015-06-27 04:39:59] log.ERROR: exception 'ReflectionException' with message 'Class WebblogController does not exist' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Container\Container.php:308 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Container\Container.php(308): ReflectionClass->__construct('WebblogControll...') #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build('WebblogControll...', Array) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('WebblogControll...', Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(983): Illuminate\Foundation\Application->make('WebblogControll...') #4 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #11 {main} [] []
[2015-06-27 04:40:48] log.ERROR: exception 'ReflectionException' with message 'Class WebblogController does not exist' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Container\Container.php:308 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Container\Container.php(308): ReflectionClass->__construct('WebblogControll...') #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build('WebblogControll...', Array) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('WebblogControll...', Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(983): Illuminate\Foundation\Application->make('WebblogControll...') #4 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #11 {main} [] []
[2015-06-27 04:40:50] log.ERROR: exception 'ReflectionException' with message 'Class WebblogController does not exist' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Container\Container.php:308 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Container\Container.php(308): ReflectionClass->__construct('WebblogControll...') #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build('WebblogControll...', Array) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('WebblogControll...', Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(983): Illuminate\Foundation\Application->make('WebblogControll...') #4 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #11 {main} [] []
[2015-06-27 04:43:20] log.ERROR: exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::finc()' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:1658 Stack trace: #0 [internal function]: Illuminate\Database\Query\Builder->__call('finc', Array) #1 [internal function]: Illuminate\Database\Query\Builder->finc('1') #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #3 [internal function]: Illuminate\Database\Eloquent\Builder->__call('finc', Array) #4 [internal function]: Illuminate\Database\Eloquent\Builder->finc('1') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2653): call_user_func_array(Array, Array) #6 [internal function]: Illuminate\Database\Eloquent\Model->__call('finc', Array) #7 [internal function]: Webblog->finc('1') #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2667): call_user_func_array(Array, Array) #9 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\WebblogController.php(25): Illuminate\Database\Eloquent\Model::__callStatic('finc', Array) #10 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\WebblogController.php(25): Webblog::finc('1') #11 [internal function]: WebblogController->show('1') #12 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('show', Array) #14 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'show', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1') #16 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-06-27 04:44:10] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-06-27 04:59:26] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 04:59:37] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/webblo...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/webblo...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 04:59:49] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 04:59:53] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 04:59:55] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:02:31] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' with message 'Controller method not found.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php:290 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(302): Illuminate\Routing\Controllers\Controller->missingMethod(Array) #1 [internal function]: Illuminate\Routing\Controllers\Controller->__call('index', Array) #2 [internal function]: GenericController->index('web_blog', '1') #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('index', Array) #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'index', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('web_blog', '1') #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2015-06-27 05:03:11] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' with message 'Controller method not found.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php:290 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(302): Illuminate\Routing\Controllers\Controller->missingMethod(Array) #1 [internal function]: Illuminate\Routing\Controllers\Controller->__call('index', Array) #2 [internal function]: GenericController->index('web_blog', '1') #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('index', Array) #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'index', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('web_blog', '1') #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2015-06-27 05:03:12] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' with message 'Controller method not found.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php:290 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(302): Illuminate\Routing\Controllers\Controller->missingMethod(Array) #1 [internal function]: Illuminate\Routing\Controllers\Controller->__call('index', Array) #2 [internal function]: GenericController->index('web_blog', '1') #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('index', Array) #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'index', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('web_blog', '1') #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2015-06-27 05:03:13] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' with message 'Controller method not found.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php:290 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(302): Illuminate\Routing\Controllers\Controller->missingMethod(Array) #1 [internal function]: Illuminate\Routing\Controllers\Controller->__call('index', Array) #2 [internal function]: GenericController->index('web_blog', '1') #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('index', Array) #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'index', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('web_blog', '1') #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2015-06-27 05:03:13] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' with message 'Controller method not found.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php:290 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(302): Illuminate\Routing\Controllers\Controller->missingMethod(Array) #1 [internal function]: Illuminate\Routing\Controllers\Controller->__call('index', Array) #2 [internal function]: GenericController->index('web_blog', '1') #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('index', Array) #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'index', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('web_blog', '1') #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2015-06-27 05:03:13] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' with message 'Controller method not found.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php:290 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(302): Illuminate\Routing\Controllers\Controller->missingMethod(Array) #1 [internal function]: Illuminate\Routing\Controllers\Controller->__call('index', Array) #2 [internal function]: GenericController->index('web_blog', '1') #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('index', Array) #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'index', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('web_blog', '1') #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2015-06-27 05:03:13] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' with message 'Controller method not found.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php:290 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(302): Illuminate\Routing\Controllers\Controller->missingMethod(Array) #1 [internal function]: Illuminate\Routing\Controllers\Controller->__call('index', Array) #2 [internal function]: GenericController->index('web_blog', '1') #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('index', Array) #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'index', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('web_blog', '1') #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2015-06-27 05:03:14] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' with message 'Controller method not found.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php:290 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(302): Illuminate\Routing\Controllers\Controller->missingMethod(Array) #1 [internal function]: Illuminate\Routing\Controllers\Controller->__call('index', Array) #2 [internal function]: GenericController->index('web_blog', '1') #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('index', Array) #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'index', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('web_blog', '1') #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2015-06-27 05:03:14] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' with message 'Controller method not found.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php:290 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(302): Illuminate\Routing\Controllers\Controller->missingMethod(Array) #1 [internal function]: Illuminate\Routing\Controllers\Controller->__call('index', Array) #2 [internal function]: GenericController->index('web_blog', '1') #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('index', Array) #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'index', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('web_blog', '1') #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2015-06-27 05:03:52] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Connection.php:272 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Connection.php(272): PDO->prepare('select * from `...') #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select * from `...', Array) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure)) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select * from `...', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect() #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array) #6 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(23): Illuminate\Database\Query\Builder->get() #7 [internal function]: GenericController->show('web_blog', '1') #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('show', Array) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'show', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('web_blog', '1') #12 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #13 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #14 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #18 {main}  Next exception 'Exception' with message 'SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: select * from ``) (Bindings: array ( ))' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select * from `...', Array) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select * from `...', Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect() #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array) #5 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(23): Illuminate\Database\Query\Builder->get() #6 [internal function]: GenericController->show('web_blog', '1') #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('show', Array) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'show', Array) #10 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('web_blog', '1') #11 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #12 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #13 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #14 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #15 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #16 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #17 {main} [] []
[2015-06-27 05:03:53] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Connection.php:272 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Connection.php(272): PDO->prepare('select * from `...') #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select * from `...', Array) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure)) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select * from `...', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect() #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array) #6 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(23): Illuminate\Database\Query\Builder->get() #7 [internal function]: GenericController->show('web_blog', '1') #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('show', Array) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'show', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('web_blog', '1') #12 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #13 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #14 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #18 {main}  Next exception 'Exception' with message 'SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: select * from ``) (Bindings: array ( ))' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select * from `...', Array) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select * from `...', Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect() #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array) #5 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(23): Illuminate\Database\Query\Builder->get() #6 [internal function]: GenericController->show('web_blog', '1') #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('show', Array) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'show', Array) #10 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('web_blog', '1') #11 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #12 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #13 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #14 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #15 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #16 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #17 {main} [] []
[2015-06-27 05:04:58] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:07:38] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:07:58] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:07:59] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:08:00] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:08:01] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:08:15] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:08:16] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:08:17] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:08:17] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:08:17] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:08:17] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:08:17] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:08:17] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:08:17] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:08:17] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:08:18] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:08:18] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:08:18] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:08:24] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:08:31] log.ERROR: exception 'ErrorException' with message 'Undefined variable: statusCode' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:28 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(28): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'C:\xampp\htdocs...', 28, Array) #1 [internal function]: GenericController->show('web_blog', '12') #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('show', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'show', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('web_blog', '12') #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-06-27 05:09:10] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:09:29] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generi', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generi') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:10:35] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:10:45] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:10:46] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:10:46] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:10:47] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:10:47] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:10:58] log.ERROR: exception 'ErrorException' with message 'Missing argument 2 for GenericController::performance()' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:34 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(34): Illuminate\Exception\Handler->handleError(2, 'Missing argumen...', 'C:\xampp\htdocs...', 34, Array) #1 [internal function]: GenericController->performance('web_blog') #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('web_blog') #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-06-27 05:10:58] log.ERROR: exception 'ErrorException' with message 'Missing argument 2 for GenericController::performance()' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:34 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(34): Illuminate\Exception\Handler->handleError(2, 'Missing argumen...', 'C:\xampp\htdocs...', 34, Array) #1 [internal function]: GenericController->performance('web_blog') #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('web_blog') #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-06-27 05:11:14] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/{{table}}" cannot reference variable name "table" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:13:31] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:43 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(43): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'C:\xampp\htdocs...', 43, Array) #1 [internal function]: GenericController->performance('web_bloqq') #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('web_bloqq') #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-06-27 05:13:41] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/{{table}}" cannot reference variable name "table" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:17:29] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:17:36] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:20:35] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 05:20:50] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/web_bl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/web_bl...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 15:08:59] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 15:47:59] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/public/generic...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/public/generic...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 15:48:31] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/public/generic...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/public/generic...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 15:48:42] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/public/generic...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/public/generic...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 15:48:52] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/public/generic...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/public/generic...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 15:53:35] log.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:40 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(40): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', 'C:\xampp\htdocs...', 40, Array) #1 [internal function]: GenericController->performance('{"web_blog","we...') #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"web_blog","we...') #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-06-27 15:53:36] log.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:40 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(40): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', 'C:\xampp\htdocs...', 40, Array) #1 [internal function]: GenericController->performance('{"web_blog","we...') #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"web_blog","we...') #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-06-27 15:53:36] log.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:40 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(40): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', 'C:\xampp\htdocs...', 40, Array) #1 [internal function]: GenericController->performance('{"web_blog","we...') #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"web_blog","we...') #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-06-27 15:53:39] log.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:40 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(40): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', 'C:\xampp\htdocs...', 40, Array) #1 [internal function]: GenericController->performance('{"web_blog","we...') #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"web_blog","we...') #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-06-27 15:53:40] log.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:40 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(40): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', 'C:\xampp\htdocs...', 40, Array) #1 [internal function]: GenericController->performance('{"web_blog","we...') #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"web_blog","we...') #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-06-27 15:53:41] log.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:40 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(40): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', 'C:\xampp\htdocs...', 40, Array) #1 [internal function]: GenericController->performance('{"web_blog","we...') #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"web_blog","we...') #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-06-27 15:53:42] log.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:40 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(40): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', 'C:\xampp\htdocs...', 40, Array) #1 [internal function]: GenericController->performance('{"web_blog","we...') #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"web_blog","we...') #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-06-27 15:53:42] log.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:40 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(40): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', 'C:\xampp\htdocs...', 40, Array) #1 [internal function]: GenericController->performance('{"web_blog","we...') #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"web_blog","we...') #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-06-27 15:53:42] log.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:40 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(40): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', 'C:\xampp\htdocs...', 40, Array) #1 [internal function]: GenericController->performance('{"web_blog","we...') #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"web_blog","we...') #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-06-27 15:53:43] log.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:40 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(40): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', 'C:\xampp\htdocs...', 40, Array) #1 [internal function]: GenericController->performance('{"web_blog","we...') #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"web_blog","we...') #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-06-27 15:53:44] log.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:40 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(40): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', 'C:\xampp\htdocs...', 40, Array) #1 [internal function]: GenericController->performance('{"web_blog","we...') #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"web_blog","we...') #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-06-27 15:53:44] log.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:40 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(40): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', 'C:\xampp\htdocs...', 40, Array) #1 [internal function]: GenericController->performance('{"web_blog","we...') #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"web_blog","we...') #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-06-27 15:53:45] log.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:40 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(40): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', 'C:\xampp\htdocs...', 40, Array) #1 [internal function]: GenericController->performance('{"web_blog","we...') #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"web_blog","we...') #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-06-27 15:53:45] log.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:40 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(40): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', 'C:\xampp\htdocs...', 40, Array) #1 [internal function]: GenericController->performance('{"web_blog","we...') #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"web_blog","we...') #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-06-27 15:54:54] log.ERROR: exception 'ErrorException' with message 'json_decode() expects parameter 1 to be string, array given' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:39 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'json_decode() e...', 'C:\xampp\htdocs...', 39, Array) #1 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(39): json_decode(Array) #2 [internal function]: GenericController->performance('{"web_blog","we...') #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"web_blog","we...') #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2015-06-27 15:54:55] log.ERROR: exception 'ErrorException' with message 'json_decode() expects parameter 1 to be string, array given' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:39 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'json_decode() e...', 'C:\xampp\htdocs...', 39, Array) #1 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(39): json_decode(Array) #2 [internal function]: GenericController->performance('{"web_blog","we...') #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"web_blog","we...') #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2015-06-27 15:54:55] log.ERROR: exception 'ErrorException' with message 'json_decode() expects parameter 1 to be string, array given' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:39 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'json_decode() e...', 'C:\xampp\htdocs...', 39, Array) #1 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(39): json_decode(Array) #2 [internal function]: GenericController->performance('{"web_blog","we...') #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"web_blog","we...') #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2015-06-27 15:55:02] log.ERROR: exception 'ErrorException' with message 'json_decode() expects parameter 1 to be string, array given' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:39 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'json_decode() e...', 'C:\xampp\htdocs...', 39, Array) #1 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(39): json_decode(Array, true) #2 [internal function]: GenericController->performance('{"web_blog","we...') #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"web_blog","we...') #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2015-06-27 15:55:02] log.ERROR: exception 'ErrorException' with message 'json_decode() expects parameter 1 to be string, array given' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:39 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'json_decode() e...', 'C:\xampp\htdocs...', 39, Array) #1 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(39): json_decode(Array, true) #2 [internal function]: GenericController->performance('{"web_blog","we...') #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"web_blog","we...') #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2015-06-27 15:56:32] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'try' (T_TRY)' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:46 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-06-27 15:56:33] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'try' (T_TRY)' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:46 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-06-27 15:56:33] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'try' (T_TRY)' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:46 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-06-27 15:56:34] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'try' (T_TRY)' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:46 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-06-27 15:56:35] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'try' (T_TRY)' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:46 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-06-27 15:56:36] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'try' (T_TRY)' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:46 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-06-27 15:56:36] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'try' (T_TRY)' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:46 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-06-27 15:56:47] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'try' (T_TRY)' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:46 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-06-27 16:08:32] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '}'' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:52 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-06-27 16:08:33] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '}'' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:52 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-06-27 16:10:04] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot access protected property Exception::$message' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:47 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-06-27 16:12:14] log.ERROR: exception 'ErrorException' with message 'Undefined variable: message' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:51 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(51): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'C:\xampp\htdocs...', 51, Array) #1 [internal function]: GenericController->performance('{"tables":["web...') #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":["web...') #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-06-27 18:11:04] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/{{table}}" cannot reference variable name "table" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/{"tabl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/%7B%22...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 18:11:49] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-06-27 19:11:26] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/generic/{"tabl...', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/generic/%7B%22...') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-06-27 19:12:41] log.ERROR: exception 'ErrorException' with message 'array_combine(): Both parameters should have an equal number of elements' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:25 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'array_combine()...', 'C:\xampp\htdocs...', 25, Array) #1 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(25): array_combine(Array, Array) #2 [internal function]: GenericController->show('{"tables":["web...', '{"id":[1,2]}') #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('show', Array) #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'show', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":["web...', '{"id":[1,2]}') #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2015-06-27 19:13:03] log.ERROR: exception 'ErrorException' with message 'array_combine(): Both parameters should have an equal number of elements' in C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php:25 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'array_combine()...', 'C:\xampp\htdocs...', 25, Array) #1 C:\xampp\htdocs\xtreme_colegios\api\app\controllers\GenericController.php(25): array_combine(Array, Array) #2 [internal function]: GenericController->show('{"tables":["web...', '{"id":[1,2]}') #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('show', Array) #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'show', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":["web...', '{"id":[1,2]}') #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #8 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #9 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2015-06-27 19:18:59] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php:102 Stack trace: #0 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 C:\xampp\htdocs\xtreme_colegios\api\vendor\symfony\routing\Symfony\Component\Routing\Matcher\UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/blog', Object(Symfony\Component\Routing\RouteCollection)) #4 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/blog') #5 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\xtreme_colegios\api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\xtreme_colegios\api\public\index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
