[2015-09-17 04:45:26] log.ERROR: exception 'ErrorException' with message 'Undefined variable: item' in /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php:73 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/app/controllers/GenericController.php(73): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 73, Array) #1 [internal function]: GenericController->performance('{"tables":{"dat...') #2 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('performance', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'performance', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('{"tables":{"dat...') #6 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/myApp/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-09-17 06:34:55] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/{{table}}" cannot reference variable name "table" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-09-17 06:34:57] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/{{table}}" cannot reference variable name "table" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-09-17 22:18:01] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Sisusuario' not found' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/SisRefUsuarioController.php:17 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:18:01] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Sisusuario' not found' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/SisRefUsuarioController.php:17 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:18:02] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Sisusuario' not found' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/SisRefUsuarioController.php:17 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:18:04] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Sisusuario' not found' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/SisRefUsuarioController.php:17 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:19:48] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Sisusuario' not found' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/SisRefUsuarioController.php:17 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:19:49] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Sisusuario' not found' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/SisRefUsuarioController.php:17 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:19:50] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Sisusuario' not found' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/SisRefUsuarioController.php:17 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:21:55] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/{{table}}" cannot reference variable name "table" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/usuarios/1/2', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/usuarios/1/2') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-09-17 22:29:27] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-09-17 22:29:28] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-09-17 22:29:31] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-09-17 22:29:44] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-09-17 22:29:45] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-09-17 22:29:50] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1') #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-09-17 22:29:52] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1') #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-09-17 22:30:33] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1') #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-09-17 22:30:34] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1') #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-09-17 22:31:02] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1') #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-09-17 22:31:03] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1') #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-09-17 22:31:03] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1') #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-09-17 22:31:04] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1') #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-09-17 22:31:04] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1') #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-09-17 22:31:04] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1') #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-09-17 22:31:07] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('34') #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-09-17 22:31:26] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('asdasd') #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-09-17 22:31:38] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('asdasd') #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-09-17 22:33:43] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function paginate() on null' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:37 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:33:44] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function paginate() on null' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:37 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:34:12] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function paginate() on null' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:37 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:35:11] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Pagination\Paginator::find()' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:37 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:35:11] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Pagination\Paginator::find()' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:37 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:39:02] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Illuminate\Database\Eloquent\Builder as array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:43 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:42:06] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Illuminate\Database\Eloquent\Builder as array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:43 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:42:07] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Illuminate\Database\Eloquent\Builder as array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:43 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:42:07] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Illuminate\Database\Eloquent\Builder as array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:43 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:42:07] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Illuminate\Database\Eloquent\Builder as array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:43 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:42:07] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Illuminate\Database\Eloquent\Builder as array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:43 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:42:07] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Illuminate\Database\Eloquent\Builder as array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:43 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:42:07] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Illuminate\Database\Eloquent\Builder as array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:43 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:42:08] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Illuminate\Database\Eloquent\Builder as array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:43 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:42:08] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Illuminate\Database\Eloquent\Builder as array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:43 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:42:08] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Illuminate\Database\Eloquent\Builder as array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:43 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:42:08] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Illuminate\Database\Eloquent\Builder as array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:43 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:43:56] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Illuminate\Database\Eloquent\Builder as array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:43 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:43:57] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Illuminate\Database\Eloquent\Builder as array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:43 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:43:57] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Illuminate\Database\Eloquent\Builder as array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:43 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:55:57] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function paginate() on null' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:37 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:55:59] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function paginate() on null' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:37 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:56:04] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function paginate() on null' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:37 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:56:15] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function paginate() on null' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:37 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:56:50] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Database\Eloquent\Collection::paginate()' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:17 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:56:53] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Database\Eloquent\Collection::paginate()' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:17 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 22:56:54] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Database\Eloquent\Collection::paginate()' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:17 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 23:07:50] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Illuminate\Database\Eloquent\Builder as array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:44 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 23:08:40] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Illuminate\Database\Eloquent\Builder as array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:44 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 23:08:41] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Illuminate\Database\Eloquent\Builder as array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:44 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 23:12:01] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Database\Eloquent\Collection::paginate()' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:37 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 23:12:02] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Database\Eloquent\Collection::paginate()' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:37 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 23:12:19] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function paginate()' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:37 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-09-17 23:51:30] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM)' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/AplRefUsuarioController.php:19 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
